### ISSUE TITLE
Use 'npm scripts prepublish' to generate plain `lib/*.js`

### ISSUE THREAD

**Issue by tetsuharuohzeki** [mizchi/arda#2]
- This enables to liberate compiled scripts (`lib/*js`) from the repository control.
- For this purpose, [the document](https://docs.npmjs.com/misc/scripts) says that `prepublish` script is suitable.

**Comment by mizchi** [comment]
Ok, I will use it so

**Comment by mizchi** [comment]
I tried this commit but it doesn't work https://github.com/mizchi/arda/commit/d950c24c2ab78a34f36189beaef073103fb1e308#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R7

Anyone do you know why it is?
